[package]
name = "mimi"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.16.0"
clap = { version = "4.5.13", features = ["derive"] }
indexmap = "2.3.0"
miette = { version = "7.2.0", features = ["fancy"] }
regex = "1.10.6"
rustc-hash = "2.0.0"
